FROM nginx:1.21.6

#NO CACHEAR EL apt-get
ARG CACHEBUST=1 
RUN apt-get update && apt-get -y upgrade

RUN echo '<html><body>Mi página de inicio personalizada en su primera versión</body></html>' > /usr/share/nginx/html/index.html

